version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps):"
    groups:
      expo:
        patterns:
          - "expo*"
          - "babel-preset-expo"
      react-native:
        patterns:
          - "react-native*"
          - "react"
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci(deps):"
