import { buildReportData, renderReportHtml } from '../../src/utils/reportGenerator';
import { Session, BaselineResult } from '../../src/types';

function makeBaseline(median: number, dayCount: number): BaselineResult {
  return { median, dayCount, values: Array(dayCount).fill(median) };
}

function makeSession(overrides: Partial<Session> = {}): Session {
  return {
    id: 'test',
    timestamp: '2026-04-15T06:30:00Z',
    durationSeconds: 300,
    rrIntervals: [],
    rmssd: 42.5,
    sdnn: 22,
    meanHr: 62,
    pnn50: 18,
    artifactRate: 0.02,
    verdict: 'go_hard',
    perceivedReadiness: null,
    trainingType: null,
    notes: null,
    sleepHours: null,
    sleepQuality: null,
    stressLevel: null,
    source: 'chest_strap',
    ...overrides,
  };
}

describe('buildReportData', () => {
  it('computes averages correctly', () => {
    const sessions = [
      makeSession({ rmssd: 30, meanHr: 60 }),
      makeSession({ rmssd: 50, meanHr: 70 }),
    ];
    const data = buildReportData(sessions, makeBaseline(40, 7), 'weekly', 5);
    expect(data.avgRmssd).toBe(40);
    expect(data.avgHr).toBe(65);
    expect(data.streak).toBe(5);
  });

  it('counts verdicts correctly', () => {
    const sessions = [
      makeSession({ verdict: 'go_hard' }),
      makeSession({ verdict: 'go_hard', id: 'b' }),
      makeSession({ verdict: 'moderate', id: 'c' }),
      makeSession({ verdict: 'rest', id: 'd' }),
    ];
    const data = buildReportData(sessions, makeBaseline(40, 7), 'weekly', 3);
    expect(data.verdictCounts.go_hard).toBe(2);
    expect(data.verdictCounts.moderate).toBe(1);
    expect(data.verdictCounts.rest).toBe(1);
  });

  it('deduplicates daily values (first session per day)', () => {
    const sessions = [
      makeSession({ id: 'morning', timestamp: '2026-04-15T06:30:00Z', rmssd: 40 }),
      makeSession({ id: 'evening', timestamp: '2026-04-15T18:00:00Z', rmssd: 45 }),
      makeSession({ id: 'nextday', timestamp: '2026-04-16T06:30:00Z', rmssd: 50 }),
    ];
    const data = buildReportData(sessions, makeBaseline(42, 7), 'weekly', 2);
    expect(data.dailyValues).toHaveLength(2);
    expect(data.dailyValues[0].rmssd).toBe(40); // first session of the day
  });

  it('handles empty sessions', () => {
    const data = buildReportData([], makeBaseline(0, 0), 'monthly', 0);
    expect(data.avgRmssd).toBe(0);
    expect(data.sessions).toHaveLength(0);
    expect(data.dailyValues).toHaveLength(0);
  });

  it('sets correct period label for weekly', () => {
    const data = buildReportData([makeSession()], makeBaseline(40, 7), 'weekly', 1);
    expect(data.periodLabel).toContain('Week of');
  });

  it('sets correct period label for monthly', () => {
    const data = buildReportData([makeSession()], makeBaseline(40, 7), 'monthly', 1);
    expect(data.periodLabel.length).toBeGreaterThan(0);
  });
});

describe('renderReportHtml', () => {
  const sessions = [
    makeSession({ id: 'a', rmssd: 40, verdict: 'go_hard', timestamp: '2026-04-14T06:30:00Z' }),
    makeSession({ id: 'b', rmssd: 35, verdict: 'moderate', timestamp: '2026-04-15T06:30:00Z' }),
  ];
  const data = buildReportData(sessions, makeBaseline(38, 7), 'weekly', 5);

  it('returns valid HTML with DOCTYPE', () => {
    const html = renderReportHtml(data);
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('</html>');
  });

  it('contains the report title', () => {
    const html = renderReportHtml(data);
    expect(html).toContain('HRV Readiness Report');
  });

  it('contains KPI values', () => {
    const html = renderReportHtml(data);
    expect(html).toContain(String(data.avgRmssd));
    expect(html).toContain(String(data.medianRmssd));
    expect(html).toContain(String(data.avgHr));
  });

  it('contains verdict distribution', () => {
    const html = renderReportHtml(data);
    expect(html).toContain('Go Hard');
    expect(html).toContain('Moderate');
    expect(html).toContain('Rest');
  });

  it('contains daily values table', () => {
    const html = renderReportHtml(data);
    expect(html).toContain('2026-04-14');
    expect(html).toContain('40.0 ms');
  });

  it('contains generation footer', () => {
    const html = renderReportHtml(data);
    expect(html).toContain('Generated by HRV Readiness Dashboard');
  });

  it('renders cleanly for empty report data', () => {
    const emptyData = buildReportData([], makeBaseline(0, 0), 'weekly', 0);
    const html = renderReportHtml(emptyData);
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('0');
  });
});
